version: "3.5"

services:
  SSLValidator:
    image: sslvalidator
    container_name: SSLValidator
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "5224:80"
      - "7224:443"
    environment:
      ASPNETCORE_URLS: "https://+,http://+"
      ASPNETCORE_HTTPS_PORT: "7224"
      ASPNETCORE_ENVIRONMENT: "Production"
  redis:
    image: redis:6.2.6
    container_name: SSLValidator.redis
    command: redis-server --requirepass "@cAHRQEHBzFlUptL@2Kt9blOMDrW1RBGzl"
    ports:
      - 5003:6379
    restart: always
